//-----------------------------------------------------------------------------
//
// Copyright (C) 2018 Arend Lammertink
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// 2D specialization for integers by casting to Fix16, generated by script.
//-----------------------------------------------------------------------------


#ifndef _interpol2d_spec_h
#define _interpol2d_spec_h

inline int8_t interpolate( int8_t x1, int8_t x2,
                            int8_t x_1, int8_t x_2, int8_t x_3, int8_t x_4,
                            int8_t y_1, int8_t y_2, int8_t y_3, int8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint8_t interpolate( int8_t x1, int8_t x2,
                            int8_t x_1, int8_t x_2, int8_t x_3, int8_t x_4,
                            uint8_t y_1, uint8_t y_2, uint8_t y_3, uint8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline int16_t interpolate( int8_t x1, int8_t x2,
                            int8_t x_1, int8_t x_2, int8_t x_3, int8_t x_4,
                            int16_t y_1, int16_t y_2, int16_t y_3, int16_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint16_t interpolate( int8_t x1, int8_t x2,
                            int8_t x_1, int8_t x_2, int8_t x_3, int8_t x_4,
                            uint16_t y_1, uint16_t y_2, uint16_t y_3, uint16_t y_4 )
{
  return static_cast< int32_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(static_cast<float>(y_1)),
                               static_cast<Fix16>(static_cast<float>(y_2)),
                               static_cast<Fix16>(static_cast<float>(y_3)),
                               static_cast<Fix16>(static_cast<float>(y_4)) ));
}


inline Fix16 interpolate( int8_t x1, int8_t x2,
                            int8_t x_1, int8_t x_2, int8_t x_3, int8_t x_4,
                            Fix16 y_1, Fix16 y_2, Fix16 y_3, Fix16 y_4 )
{
  return static_cast< Fix16 >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline float interpolate( int8_t x1, int8_t x2,
                            int8_t x_1, int8_t x_2, int8_t x_3, int8_t x_4,
                            float y_1, float y_2, float y_3, float y_4 )
{
  return static_cast< float >(
                  interpolate( static_cast<float>(x1),
                               static_cast<float>(x2),
                               static_cast<float>(x_1),
                               static_cast<float>(x_2),
                               static_cast<float>(x_3),
                               static_cast<float>(x_4),
                               static_cast<float>(y_1),
                               static_cast<float>(y_2),
                               static_cast<float>(y_3),
                               static_cast<float>(y_4) ));
}


inline double interpolate( int8_t x1, int8_t x2,
                            int8_t x_1, int8_t x_2, int8_t x_3, int8_t x_4,
                            double y_1, double y_2, double y_3, double y_4 )
{
  return static_cast< double >(
                  interpolate( static_cast<double>(x1),
                               static_cast<double>(x2),
                               static_cast<double>(x_1),
                               static_cast<double>(x_2),
                               static_cast<double>(x_3),
                               static_cast<double>(x_4),
                               static_cast<double>(y_1),
                               static_cast<double>(y_2),
                               static_cast<double>(y_3),
                               static_cast<double>(y_4) ));
}


inline int8_t interpolate( uint8_t x1, uint8_t x2,
                            uint8_t x_1, uint8_t x_2, uint8_t x_3, uint8_t x_4,
                            int8_t y_1, int8_t y_2, int8_t y_3, int8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint8_t interpolate( uint8_t x1, uint8_t x2,
                            uint8_t x_1, uint8_t x_2, uint8_t x_3, uint8_t x_4,
                            uint8_t y_1, uint8_t y_2, uint8_t y_3, uint8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline int16_t interpolate( uint8_t x1, uint8_t x2,
                            uint8_t x_1, uint8_t x_2, uint8_t x_3, uint8_t x_4,
                            int16_t y_1, int16_t y_2, int16_t y_3, int16_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint16_t interpolate( uint8_t x1, uint8_t x2,
                            uint8_t x_1, uint8_t x_2, uint8_t x_3, uint8_t x_4,
                            uint16_t y_1, uint16_t y_2, uint16_t y_3, uint16_t y_4 )
{
  return static_cast< int32_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(static_cast<float>(y_1)),
                               static_cast<Fix16>(static_cast<float>(y_2)),
                               static_cast<Fix16>(static_cast<float>(y_3)),
                               static_cast<Fix16>(static_cast<float>(y_4)) ));
}


inline Fix16 interpolate( uint8_t x1, uint8_t x2,
                            uint8_t x_1, uint8_t x_2, uint8_t x_3, uint8_t x_4,
                            Fix16 y_1, Fix16 y_2, Fix16 y_3, Fix16 y_4 )
{
  return static_cast< Fix16 >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline float interpolate( uint8_t x1, uint8_t x2,
                            uint8_t x_1, uint8_t x_2, uint8_t x_3, uint8_t x_4,
                            float y_1, float y_2, float y_3, float y_4 )
{
  return static_cast< float >(
                  interpolate( static_cast<float>(x1),
                               static_cast<float>(x2),
                               static_cast<float>(x_1),
                               static_cast<float>(x_2),
                               static_cast<float>(x_3),
                               static_cast<float>(x_4),
                               static_cast<float>(y_1),
                               static_cast<float>(y_2),
                               static_cast<float>(y_3),
                               static_cast<float>(y_4) ));
}


inline double interpolate( uint8_t x1, uint8_t x2,
                            uint8_t x_1, uint8_t x_2, uint8_t x_3, uint8_t x_4,
                            double y_1, double y_2, double y_3, double y_4 )
{
  return static_cast< double >(
                  interpolate( static_cast<double>(x1),
                               static_cast<double>(x2),
                               static_cast<double>(x_1),
                               static_cast<double>(x_2),
                               static_cast<double>(x_3),
                               static_cast<double>(x_4),
                               static_cast<double>(y_1),
                               static_cast<double>(y_2),
                               static_cast<double>(y_3),
                               static_cast<double>(y_4) ));
}


inline int8_t interpolate( int16_t x1, int16_t x2,
                            int16_t x_1, int16_t x_2, int16_t x_3, int16_t x_4,
                            int8_t y_1, int8_t y_2, int8_t y_3, int8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint8_t interpolate( int16_t x1, int16_t x2,
                            int16_t x_1, int16_t x_2, int16_t x_3, int16_t x_4,
                            uint8_t y_1, uint8_t y_2, uint8_t y_3, uint8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline int16_t interpolate( int16_t x1, int16_t x2,
                            int16_t x_1, int16_t x_2, int16_t x_3, int16_t x_4,
                            int16_t y_1, int16_t y_2, int16_t y_3, int16_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint16_t interpolate( int16_t x1, int16_t x2,
                            int16_t x_1, int16_t x_2, int16_t x_3, int16_t x_4,
                            uint16_t y_1, uint16_t y_2, uint16_t y_3, uint16_t y_4 )
{
  return static_cast< int32_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(static_cast<float>(y_1)),
                               static_cast<Fix16>(static_cast<float>(y_2)),
                               static_cast<Fix16>(static_cast<float>(y_3)),
                               static_cast<Fix16>(static_cast<float>(y_4)) ));
}


inline Fix16 interpolate( int16_t x1, int16_t x2,
                            int16_t x_1, int16_t x_2, int16_t x_3, int16_t x_4,
                            Fix16 y_1, Fix16 y_2, Fix16 y_3, Fix16 y_4 )
{
  return static_cast< Fix16 >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline float interpolate( int16_t x1, int16_t x2,
                            int16_t x_1, int16_t x_2, int16_t x_3, int16_t x_4,
                            float y_1, float y_2, float y_3, float y_4 )
{
  return static_cast< float >(
                  interpolate( static_cast<float>(x1),
                               static_cast<float>(x2),
                               static_cast<float>(x_1),
                               static_cast<float>(x_2),
                               static_cast<float>(x_3),
                               static_cast<float>(x_4),
                               static_cast<float>(y_1),
                               static_cast<float>(y_2),
                               static_cast<float>(y_3),
                               static_cast<float>(y_4) ));
}


inline double interpolate( int16_t x1, int16_t x2,
                            int16_t x_1, int16_t x_2, int16_t x_3, int16_t x_4,
                            double y_1, double y_2, double y_3, double y_4 )
{
  return static_cast< double >(
                  interpolate( static_cast<double>(x1),
                               static_cast<double>(x2),
                               static_cast<double>(x_1),
                               static_cast<double>(x_2),
                               static_cast<double>(x_3),
                               static_cast<double>(x_4),
                               static_cast<double>(y_1),
                               static_cast<double>(y_2),
                               static_cast<double>(y_3),
                               static_cast<double>(y_4) ));
}


inline int8_t interpolate( uint16_t x1, uint16_t x2,
                            uint16_t x_1, uint16_t x_2, uint16_t x_3, uint16_t x_4,
                            int8_t y_1, int8_t y_2, int8_t y_3, int8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(static_cast<float>(x1)),
                               static_cast<Fix16>(static_cast<float>(x2)),
                               static_cast<Fix16>(static_cast<float>(x_1)),
                               static_cast<Fix16>(static_cast<float>(x_2)),
                               static_cast<Fix16>(static_cast<float>(x_3)),
                               static_cast<Fix16>(static_cast<float>(x_4)),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint8_t interpolate( uint16_t x1, uint16_t x2,
                            uint16_t x_1, uint16_t x_2, uint16_t x_3, uint16_t x_4,
                            uint8_t y_1, uint8_t y_2, uint8_t y_3, uint8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(static_cast<float>(x1)),
                               static_cast<Fix16>(static_cast<float>(x2)),
                               static_cast<Fix16>(static_cast<float>(x_1)),
                               static_cast<Fix16>(static_cast<float>(x_2)),
                               static_cast<Fix16>(static_cast<float>(x_3)),
                               static_cast<Fix16>(static_cast<float>(x_4)),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline int16_t interpolate( uint16_t x1, uint16_t x2,
                            uint16_t x_1, uint16_t x_2, uint16_t x_3, uint16_t x_4,
                            int16_t y_1, int16_t y_2, int16_t y_3, int16_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(static_cast<float>(x1)),
                               static_cast<Fix16>(static_cast<float>(x2)),
                               static_cast<Fix16>(static_cast<float>(x_1)),
                               static_cast<Fix16>(static_cast<float>(x_2)),
                               static_cast<Fix16>(static_cast<float>(x_3)),
                               static_cast<Fix16>(static_cast<float>(x_4)),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint16_t interpolate( uint16_t x1, uint16_t x2,
                            uint16_t x_1, uint16_t x_2, uint16_t x_3, uint16_t x_4,
                            uint16_t y_1, uint16_t y_2, uint16_t y_3, uint16_t y_4 )
{
  return static_cast< int32_t >(
                  interpolate( static_cast<Fix16>(static_cast<float>(x1)),
                               static_cast<Fix16>(static_cast<float>(x2)),
                               static_cast<Fix16>(static_cast<float>(x_1)),
                               static_cast<Fix16>(static_cast<float>(x_2)),
                               static_cast<Fix16>(static_cast<float>(x_3)),
                               static_cast<Fix16>(static_cast<float>(x_4)),
                               static_cast<Fix16>(static_cast<float>(y_1)),
                               static_cast<Fix16>(static_cast<float>(y_2)),
                               static_cast<Fix16>(static_cast<float>(y_3)),
                               static_cast<Fix16>(static_cast<float>(y_4)) ));
}


inline Fix16 interpolate( uint16_t x1, uint16_t x2,
                            uint16_t x_1, uint16_t x_2, uint16_t x_3, uint16_t x_4,
                            Fix16 y_1, Fix16 y_2, Fix16 y_3, Fix16 y_4 )
{
  return static_cast< Fix16 >(
                  interpolate( static_cast<Fix16>(static_cast<float>(x1)),
                               static_cast<Fix16>(static_cast<float>(x2)),
                               static_cast<Fix16>(static_cast<float>(x_1)),
                               static_cast<Fix16>(static_cast<float>(x_2)),
                               static_cast<Fix16>(static_cast<float>(x_3)),
                               static_cast<Fix16>(static_cast<float>(x_4)),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline float interpolate( uint16_t x1, uint16_t x2,
                            uint16_t x_1, uint16_t x_2, uint16_t x_3, uint16_t x_4,
                            float y_1, float y_2, float y_3, float y_4 )
{
  return static_cast< float >(
                  interpolate( static_cast<float>(x1),
                               static_cast<float>(x2),
                               static_cast<float>(x_1),
                               static_cast<float>(x_2),
                               static_cast<float>(x_3),
                               static_cast<float>(x_4),
                               static_cast<float>(y_1),
                               static_cast<float>(y_2),
                               static_cast<float>(y_3),
                               static_cast<float>(y_4) ));
}


inline double interpolate( uint16_t x1, uint16_t x2,
                            uint16_t x_1, uint16_t x_2, uint16_t x_3, uint16_t x_4,
                            double y_1, double y_2, double y_3, double y_4 )
{
  return static_cast< double >(
                  interpolate( static_cast<double>(x1),
                               static_cast<double>(x2),
                               static_cast<double>(x_1),
                               static_cast<double>(x_2),
                               static_cast<double>(x_3),
                               static_cast<double>(x_4),
                               static_cast<double>(y_1),
                               static_cast<double>(y_2),
                               static_cast<double>(y_3),
                               static_cast<double>(y_4) ));
}


inline int8_t interpolate( Fix16 x1, Fix16 x2,
                            Fix16 x_1, Fix16 x_2, Fix16 x_3, Fix16 x_4,
                            int8_t y_1, int8_t y_2, int8_t y_3, int8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint8_t interpolate( Fix16 x1, Fix16 x2,
                            Fix16 x_1, Fix16 x_2, Fix16 x_3, Fix16 x_4,
                            uint8_t y_1, uint8_t y_2, uint8_t y_3, uint8_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline int16_t interpolate( Fix16 x1, Fix16 x2,
                            Fix16 x_1, Fix16 x_2, Fix16 x_3, Fix16 x_4,
                            int16_t y_1, int16_t y_2, int16_t y_3, int16_t y_4 )
{
  return static_cast< int16_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(y_1),
                               static_cast<Fix16>(y_2),
                               static_cast<Fix16>(y_3),
                               static_cast<Fix16>(y_4) ));
}


inline uint16_t interpolate( Fix16 x1, Fix16 x2,
                            Fix16 x_1, Fix16 x_2, Fix16 x_3, Fix16 x_4,
                            uint16_t y_1, uint16_t y_2, uint16_t y_3, uint16_t y_4 )
{
  return static_cast< int32_t >(
                  interpolate( static_cast<Fix16>(x1),
                               static_cast<Fix16>(x2),
                               static_cast<Fix16>(x_1),
                               static_cast<Fix16>(x_2),
                               static_cast<Fix16>(x_3),
                               static_cast<Fix16>(x_4),
                               static_cast<Fix16>(static_cast<float>(y_1)),
                               static_cast<Fix16>(static_cast<float>(y_2)),
                               static_cast<Fix16>(static_cast<float>(y_3)),
                               static_cast<Fix16>(static_cast<float>(y_4)) ));
}


#endif
